return {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPre", "BufNewFile" },
    cmd = { "TSUpdate", "TSModuleInfo" },
    opts = {
        ensure_installed = {
            "asm",
            "bash",
            "c",
            "c_sharp",
            "capnp",
            "cmake",
            "cpp",
            "css",
            "diff",
            "disassembly",
            "dockerfile",
            "dot",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "git_config",
            "git_rebase",
            "go",
            "graphql",
            "haskell",
            "hcl",
            "html",
            "http",
            "ini",
            "java",
            "javascript",
            "json",
            "json5",
            "jq",
            "just",
            "kotlin",
            "latex",
            "linkerscript",
            "llvm",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "nasm",
            "ninja",
            "nix",
            "objc",
            "objdump",
            "perl",
            "php",
            "proto",
            "python",
            "regex",
            "ron",
            "ruby",
            "rust",
            "scala",
            "scss",
            "sql",
            "ssh_config",
            "svelte",
            "swift",
            "terraform",
            "tmux",
            "toml",
            "tsx",
            "typescript",
            "typst",
            "vim",
            "vimdoc",
            "vue",
            "xml",
            "yaml",
            "zig",
        },
        auto_install = true,
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
        rainbow = {
            enable = true,
            disable = { "html" },
            extended_mode = false,
            max_file_lines = nil,
        },
        incremental_selection = { enable = true },
        indent = { enable = false },
    },
    config = function(_, opts)
        require("nvim-treesitter.configs").setup(opts)
    end,
}
